sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
script: yarn
